before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    ignore:
      - goos: windows
        goarch: arm64
    binary: caniuse

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: 32-bit
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

nfpms:
  - id: caniuse
    package_name: caniuse
    homepage: https://github.com/fkhadra/caniuse
    maintainer: Fadi Khadra <fdkhadra@gmail.com>
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/local/bin


checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    tap:
      owner: fkhadra
      name: homebrew-cli
    homepage: 'https://github.com/fkhadra/caniuse/'
    description: 'Beautiful TUI for caniuse'
